version: "2.15.1"
services:

  postfix:
    container_name: "mail-postfix"
    image: catatnight/postfix
    restart: "always"
    expose:
      - "25"
    environment:
      maildomain: "wpdiaries.com" # replace with your own server name instead of example.com
      smtp_user: "admin:pwd" # username and password for SMTP
 #   volumes:
 #     - "/opt/projects/mail/volumes/domainkeys:/etc/opendkim/domainkeys"
    
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "habrdb"
      POSTGRES_USER: "habrpguser"
      POSTGRES_PASSWORD: "pgpwd4habr"
    ports:
      - "5431:5432"
 #   volume:
  #   - "C:\\habbits_data:/var/lib/postgresql/data"

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: "rabbitmq"
    restart: "always"
    environment:
       RABBITMQ_DEFAULT_USER: "rmuser"
       RABBITMQ_DEFAULT_PASS: "rmpassword"
    ports:
      - "15672:15672"

